### PR TITLE
Add "How FROM works" page

### PR DESCRIPTION
**Pull request by s-blu**

### CODE REVIEW

**Comment by AB1908** [comment]
IMO this overlaps a bit with what docs should cover. Would you agree? I think dataview needs three things: a getting started guide, docs for reference, and this example vault and something like this falls more on the getting started side. Is that something you're planning to work towards?

**Comment by s-blu** [comment]
@AB1908 no, I do agree with you. It's rather difficult to draw a line between "examples" and "documentation", in my opinion, but yes, since this page is completely explonational without working examples, you're right. This should go into the official docs.

I'd highly prefer if there's only one place for reference, so I certainly do not plan to work towards a documentation duplication. I orientated myself on the documentation to add some examples, but maybe it's better to enhance the documentation with these hints. I wonder if it'd be possible to structure [the query page](https://blacksmithgu.github.io/obsidian-dataview/query/queries) in a bit more beginners friendly way - I think its rather technical right now.

**Comment by s-blu** [comment]
@AB1908 I hopped over to the dataview repo, finally forked it :D, and tried out a rough refactor that'd allow the integration of the informations of the "How" page to the documentation. Maybe you want to [take a look](https://github.com/blacksmithgu/obsidian-dataview/compare/master...s-blu:obsidian-dataview:docsQueryExplanationRework) if that'd be a possible way to go 

The main point is the split up of the one reference query page into an own section. I personally always was confused about the existence of "Data Querying" and "Query Language Reference -> Queries" anyway and never knew where to look. 

grafik

**Comment by s-blu** [comment]
I've shifted the focus back to the example page and added links to the sections in the documentation instead of providing own pages.

**Pull request merged**
