### PR TITLE
add the difference between `=[[]]` and `=this`. Add .obsidian\themes in gitignore

### PR DESCRIPTION
**Pull request by ooker777**
- add the difference between `=[[]]` and `=this`
- add the difference between `=[[]]` and `=this`. Add .obsidian\themes in gitignore

### CODE REVIEW

**Comment by s-blu** [comment]
Hello ooker, 
this PR is a draft now for quite some while. Do you plan to come back to it?

**Comment by ooker777** [comment]
Which part do you see it's unfinished?

**Comment by s-blu** [comment]
> Which part do you see it's unfinished?

@ooker777 You marked this PR as a "draft", a work in progress that is neither reviewable nor mergable:

grafik

Therefor this is not a assessment from myself but the current state of your PR.

**Comment by ooker777** [comment]
I see. I must not know how to use this back then. I've undrafted it. Do you think it's good to merge now?

**Pull request merged**
